---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Sample Template Infra for Dev'
Parameters:

  # Ownership
  
  Owner:
    Description: Name for contact purpose
    Type: String
    Default: Name or TeamName
  Project:
    Description: Name of the project
    Type: String
    Default: eg. Project Blah Blah
  EnvironmentName:
    Description: An environment / project name that will be prefixed to resource names
    Type: String

  # VPC and Subnets

  VpcID:
    Description: List of existing VPC
    Type: AWS::EC2::VPC::Id
    ConstraintDescription: must be the name of an existing VPC
  PublicSubnet1:
    Description: IP range (CIDR notation) for the public subnet in the AZ
    Type: AWS::EC2::Subnet::Id
    ConstraintDescription: must be the name of an existing Subnet

  # Key Pairs and Instance

  KeyName:
    Description: Existing EC2 KeyPair to enable SSH access to the instances
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  InstanceType:
    Description: Instance type for your Dev Server
    Type: String
    Default: t2.small
    AllowedValues:
    - t1.micro
    - t2.nano
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    - m1.small
    - m1.medium
    - m1.large
    - m1.xlarge
    - m2.xlarge
    - m2.2xlarge
    - m2.4xlarge
    - m3.medium
    - m3.large
    - m3.xlarge
    - m3.2xlarge
    - m4.large
    - m4.xlarge
    - m4.2xlarge
    - m4.4xlarge
    - m4.10xlarge
    - m5.large
    - m5.xlarge
    ConstraintDescription: must be a valid EC2 instance type. 

  # Remote Access Network

  SSHInbound1:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 13.250.116.222/32
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.   
Mappings:
  AWSInstanceType2Arch:
    t1.micro:
      Arch: HVM64
    t2.nano:
      Arch: HVM64
    t2.micro:
      Arch: HVM64
    t2.small:
      Arch: HVM64 
    t2.medium:
      Arch: HVM64
    t2.large:
      Arch: HVM64
    m1.small:
      Arch: HVM64
    m1.medium:
      Arch: HVM64
    m1.large:
      Arch: HVM64
    m1.xlarge:
      Arch: HVM64
    m2.xlarge:
      Arch: HVM64
    m2.2xlarge:
      Arch: HVM64
    m2.4xlarge:
      Arch: HVM64
    m3.medium:
      Arch: HVM64
    m3.large:
      Arch: HVM64
    m3.xlarge:
      Arch: HVM64
    m3.2xlarge:
      Arch: HVM64
    m4.large:
      Arch: HVM64
    m4.xlarge:
      Arch: HVM64
    m4.2xlarge:
      Arch: HVM64
    m4.4xlarge:
      Arch: HVM64
    m4.10xlarge:
      Arch: HVM64
    m5.large:
      Arch: HVM64
    m5.xlarge:
      Arch: HVM64      
  AWSRegionArch2AMI:
    ap-southeast-1:
      HVM64: ami-08569b978cc4dfa10
      HVMG2: ami-0be9df32ae9f92309
    ap-southeast-2:
      HVM64: ami-09b42976632b27e9b
      HVMG2: ami-0a9ce9fecc3d1daf8
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType:
        Ref: InstanceType
      SecurityGroups:
      - Ref: InstanceSecurityGroup
      KeyName:
        Ref: KeyName
      ImageId:
        Fn::FindInMap:
        - AWSRegionArch2AMI
        - Ref: AWS::Region
        - Fn::FindInMap:
          - AWSInstanceType2Arch
          - Ref: InstanceType
          - Arch
      Tags:
      - Key: Name
        Value: !Ref EnvironmentName
      - Key: Project
        Value: !Ref Project
      - Key: Contact
        Value: !Ref Owner
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 
          Ref: SSHInbound1
      Tags:
      - Key: Name
        Value: !Ref EnvironmentName
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Environment
      Parameters:
      - EnvironmentName
    - Label:
        default: Ownership
      Parameters:
      - Owner
      - Project
    - Label:
        default: Network
      Parameters:
      - VpcID
      - PublicSubnet1
    - Label:
        default: EC2
      Parameters:
      - KeyName
      - InstanceType
    - Label:
        default: Remote Access
      Parameters:
      - SSHInbound1
    ParameterLabels:
      EnvironmentName:
        default: Environment Name
      Owner:
        default: Team or Individual Owner
      Project:
        default: Project
      VpcID:
        default: VPC ID
      PublicSubnet1Cidr:
        default: Subnet 1
      KeyName:
        default: Key Pair
      InstanceType:
        default: Instance Type
      SSHInbound1:
        default: Yondu IP 1      